const countryCodes = {
    "Afghanistan": "AF",
    "Australia": "AU",
    "Austria": "AT",
    "Azerbaijan": "AZ",
    "Bangladesh": "BD",
    "Bhutan": "BT",
    "Canada": "CA",
    "India": "IN",
    "Japan": "JP",
    "Mexico": "MX",
    "Russia": "RU",
    "Singapore": "SG",
    "South Africa": "ZA",
    "South Korea": "KR",
    "Spain": "ES",
    "Sri Lanka": "LK",
    "United Kingdom": "GB",
    "United States": "US",
    "Germany": "DE"
};
